import type { User, Post, TrendingTopic, SuggestedUser, Notification } from '@/types'

export const CURRENT_USER: User = {
  id: '1',
  name: 'Alex Rivera',
  username: 'arivera_design',
  avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=80&h=80&fit=crop&crop=face',
  bio: 'Digital Architect & Product Designer. Crafting seamless experiences at the intersection of technology and human connection. Focused on the future of social interaction. 🚀',
  location: 'San Francisco, CA',
  website: 'alexrivera.io',
  joinedDate: 'October 2021',
  following: 1284,
  followers: 42500,
  posts: 892,
  isOnline: true,
}

export const USERS: User[] = [
  {
    id: '2',
    name: 'Sarah Chen',
    username: 'sarahc_design',
    avatar: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=80&h=80&fit=crop&crop=face',
    following: 892, followers: 15600, posts: 431,
  },
  {
    id: '3',
    name: 'Jordan Smith',
    username: 'jsmith_tech',
    avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=80&h=80&fit=crop&crop=face',
    following: 234, followers: 8900, posts: 218,
  },
  {
    id: '4',
    name: 'Elena Rodriguez',
    username: 'elena_vision',
    avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=80&h=80&fit=crop&crop=face',
    following: 1100, followers: 32000, posts: 764,
  },
  {
    id: '5',
    name: 'Marcus Wright',
    username: 'mwright',
    avatar: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=80&h=80&fit=crop&crop=face',
    following: 567, followers: 9200, posts: 312,
  },
  {
    id: '6',
    name: 'Sophia Lee',
    username: 'slee_creative',
    avatar: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=80&h=80&fit=crop&crop=face',
    following: 743, followers: 21000, posts: 589,
  },
  {
    id: '7',
    name: 'David Kim',
    username: 'dkim_dev',
    avatar: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=80&h=80&fit=crop&crop=face',
    following: 321, followers: 6700, posts: 177,
  },
]

export const POSTS: Post[] = [
  {
    id: '1',
    author: CURRENT_USER,
    content: 'Just finished building the new layout for ConnectX. The transition to React 18 concurrent features has been a game changer for performance. What do you all think about the new UI? 🚀',
    images: ['https://images.unsplash.com/photo-1593642632559-0c6d3fc62b89?w=600&h=400&fit=crop'],
    timeAgo: '2h',
    createdAt: '2024-01-15T10:00:00Z',
    likes: 1200,
    comments: 48,
    shares: 124,
    isLiked: false,
    isBookmarked: false,
  },
  {
    id: '2',
    author: USERS[0],
    content: 'Deeply inspired by the minimalist aesthetic trends for 2024. Clean lines, functional whitespace, and high-contrast typography are making a huge comeback. Design is moving back to its functional roots.',
    timeAgo: '4h',
    createdAt: '2024-01-15T08:00:00Z',
    likes: 856,
    comments: 12,
    shares: 32,
    isLiked: true,
    isBookmarked: false,
  },
  {
    id: '3',
    author: USERS[1],
    content: 'Coffee shop office for the day. There\'s something about the ambient noise that just hits different when you need to focus on deep work. ☕💻',
    images: ['https://images.unsplash.com/photo-1593640495253-23196b27a87f?w=600&h=400&fit=crop'],
    timeAgo: '6h',
    createdAt: '2024-01-15T06:00:00Z',
    likes: 432,
    comments: 18,
    shares: 15,
    isLiked: false,
    isBookmarked: true,
  },
  {
    id: '4',
    author: USERS[2],
    content: "Don't forget to take breaks. Your productivity is a marathon, not a sprint. Step away from the screen for 10 minutes every hour. Your brain will thank you.",
    timeAgo: '8h',
    createdAt: '2024-01-15T04:00:00Z',
    likes: 2100,
    comments: 156,
    shares: 410,
    isLiked: false,
    isBookmarked: false,
  },
  {
    id: '5',
    author: USERS[3],
    content: 'Just shipped a massive performance update. 40% reduction in bundle size and 60% faster initial load. The devil is in the details. 🔥 #WebPerf #React',
    timeAgo: '10h',
    createdAt: '2024-01-15T02:00:00Z',
    likes: 3200,
    comments: 89,
    shares: 267,
    isLiked: true,
    isBookmarked: true,
  },
  {
    id: '6',
    author: CURRENT_USER,
    content: 'The best designs aren\'t noticed; they\'re felt. Simplicity is the ultimate sophistication in the digital age.',
    timeAgo: '5h',
    createdAt: '2024-01-15T07:00:00Z',
    likes: 842,
    comments: 12,
    shares: 89,
    isLiked: false,
    isBookmarked: false,
  },
  {
    id: '7',
    author: CURRENT_USER,
    content: 'Coffee and Figma. The perfect start to a Monday morning. ☕🎨 #DesignLife #ProductDesign',
    timeAgo: '1d',
    createdAt: '2024-01-14T10:00:00Z',
    likes: 2100,
    comments: 64,
    shares: 234,
    isLiked: true,
    isBookmarked: false,
  },
]

export const TRENDING: TrendingTopic[] = [
  { category: 'TECHNOLOGY', topic: '#ReactConf2024', postCount: '15.4k posts' },
  { category: 'DESIGN', topic: 'Minimalist UI', postCount: '8.2k posts' },
  { category: 'DEVELOPMENT', topic: 'TailwindCSS', postCount: '22.1k posts' },
  { category: 'CAREER', topic: 'RemoteWork', postCount: '5.3k posts' },
  { category: 'AI', topic: '#GenerativeDesign', postCount: '11.7k posts' },
]

export const SUGGESTED_USERS: SuggestedUser[] = [
  { id: '5', name: 'Marcus Wright', username: 'mwright', avatar: USERS[3].avatar },
  { id: '6', name: 'Sophia Lee', username: 'slee_creative', avatar: USERS[4].avatar },
  { id: '7', name: 'David Kim', username: 'dkim_dev', avatar: USERS[5].avatar },
]

export const NOTIFICATIONS: Notification[] = [
  {
    id: '1',
    type: 'like',
    user: USERS[0],
    content: 'liked your post about React 18 features',
    timeAgo: '2m',
    read: false,
  },
  {
    id: '2',
    type: 'follow',
    user: USERS[3],
    content: 'started following you',
    timeAgo: '15m',
    read: false,
  },
  {
    id: '3',
    type: 'comment',
    user: USERS[1],
    content: 'commented: "This is exactly what I needed to read today!"',
    timeAgo: '1h',
    read: false,
  },
  {
    id: '4',
    type: 'share',
    user: USERS[2],
    content: 'reposted your post about minimalist design',
    timeAgo: '3h',
    read: true,
  },
  {
    id: '5',
    type: 'mention',
    user: USERS[4],
    content: 'mentioned you in a post about UI trends',
    timeAgo: '5h',
    read: true,
  },
]
